# Converts dark-ink-on-light artwork into an LVGL 8 image (2-bit indexed):
# ink becomes $Color on black. Usage:
#   .\tools\boot-image.ps1 -Source art.png -Out include\boot_image.h
param(
    [Parameter(Mandatory)][string]$Source,
    [string]$Out = "$PSScriptRoot\..\include\boot_image.h",
    [string]$Color = 'E01010',
    [int]$Height = 240,
    [string]$Preview,  # optional PNG of the result
    [ValidateSet(0, 90, 180, 270)][int]$Rotate = 0  # clockwise; 90/270 = portrait on the landscape panel
)
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing

$src = [System.Drawing.Bitmap]::FromFile((Resolve-Path $Source))
if ($Rotate) { $src.RotateFlip("Rotate$($Rotate)FlipNone") }
$w = [int][math]::Round($src.Width * $Height / $src.Height)
$img = New-Object System.Drawing.Bitmap $w, $Height
$g = [System.Drawing.Graphics]::FromImage($img)
$g.InterpolationMode = 'HighQualityBicubic'
$g.DrawImage($src, 0, 0, $w, $Height)
$g.Dispose(); $src.Dispose()

# Palette: black -> full colour in 4 steps. lv_color32_t byte order is B, G, R, A.
$r = [Convert]::ToInt32($Color.Substring(0, 2), 16)
$gr = [Convert]::ToInt32($Color.Substring(2, 2), 16)
$bl = [Convert]::ToInt32($Color.Substring(4, 2), 16)
$bytes = New-Object System.Collections.Generic.List[byte]
foreach ($k in 0..3) { foreach ($c in $bl, $gr, $r) { $bytes.Add([byte]($c * $k / 3)) }; $bytes.Add(255) }

# Ink = darkness of the brightest channel, so coloured marks (e.g. a blue watermark) drop out.
for ($y = 0; $y -lt $Height; $y++) {
    $acc = 0; $bits = 0
    for ($x = 0; $x -lt $w; $x++) {
        $p = $img.GetPixel($x, $y)
        $ink = 255 - [math]::Max($p.R, [math]::Max($p.G, $p.B))
        $level = if ($ink -lt 60) { 0 } elseif ($ink -lt 110) { 1 } elseif ($ink -lt 160) { 2 } else { 3 }
        if ($Preview) { $img.SetPixel($x, $y, [System.Drawing.Color]::FromArgb($r * $level / 3, $gr * $level / 3, $bl * $level / 3)) }
        $acc = ($acc -shl 2) -bor $level; $bits += 2
        if ($bits -eq 8) { $bytes.Add([byte]$acc); $acc = 0; $bits = 0 }
    }
    if ($bits) { $bytes.Add([byte]($acc -shl (8 - $bits))) }  # pad row to a byte
}
if ($Preview) { $img.Save($Preview) }
$img.Dispose()

$hex = for ($i = 0; $i -lt $bytes.Count; $i += 16) {
    '  ' + (($bytes[$i..([math]::Min($i + 15, $bytes.Count - 1))] | ForEach-Object { '0x{0:x2}' -f $_ }) -join ', ') + ','
}
@"
#pragma once
// Generated by tools/boot-image.ps1 from $(Split-Path $Source -Leaf). Do not edit.
#include <lvgl.h>

static const uint8_t boot_image_map[] = {
$($hex -join "`n")
};

static const lv_img_dsc_t boot_image = {
  {LV_IMG_CF_INDEXED_2BIT, 0, 0, $w, $Height},
  sizeof(boot_image_map),
  boot_image_map,
};
"@ | Set-Content -Encoding utf8 $Out
"wrote $Out ($w x $Height, $($bytes.Count) bytes)"
